// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fileps.proto

package chunker

import (
	fmt "fmt"
	math "math"
	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *FileMeta) Validate() error {
	return nil
}
func (this *Chunk) Validate() error {
	return nil
}
